version: "3.9"

services:
  bladerunner:
    build: .
    restart: on-failure
    ports:
      - "6969:6969"
    depends_on:
      - redis
    environment:
      - "DEBUG=express-session"
      - "flag=maple{blade_runner_2049_jf834gnc_0YFR343V8}"
      - "port=6969"
  redis:
    image: "redis:alpine"